"""Reusable SecureEdgeVision domain package.

This package is intentionally side-effect free. Service applications import
domain logic from here; importing it must not start a server or load a model.
"""

from secureedge.canonical import canonical_event_bytes
from secureedge.contracts import (
    Detection,
    DetectionEvent,
    FrameMetadata,
    ModelMetadata,
    NodeHeartbeat,
    NodeRegistration,
    PerformanceMetrics,
    SignedDetectionEnvelope,
)
from secureedge.crypto import (
    KeyMaterialError,
    encode_public_key,
    generate_private_key,
    load_private_key,
    load_public_key,
    serialize_private_key,
    sign_detection_event,
    verify_detection_envelope,
)
from secureedge.security import (
    EventSecurityConfigurationError,
    EventSecurityDecision,
    EventSecurityReason,
    EventSecurityRejection,
    ReplayFreshnessPolicy,
)
from secureedge.transport import (
    ACCEPTED_STATUS,
    DETECTION_PATH,
    HEARTBEAT_PATH,
    EventTransport,
    HeartbeatError,
    HeartbeatFactory,
    SignedWorkerRunner,
    SignedWorkerTransport,
    TransportError,
    WaitFunction,
    WorkerHeartbeatLifecycle,
)
from secureedge.vision import (
    DetectorBackend,
    LocalYOLODetector,
    LocalYoloDetector,
    ModelFactory,
    VisionError,
    VisionResult,
    YoloDetector,
    create_yolo_detector,
    detect_frame,
    infer_frame,
)
from secureedge.worker import (
    CaptureBackend,
    CapturedFrame,
    CaptureFactory,
    EventSink,
    FrameDetector,
    FrameSource,
    IdentifierFactory,
    MonotonicClock,
    OpenCvFrameSource,
    PrivacyWorkerPipeline,
    UtcClock,
    WorkerLifecycle,
    WorkerPipelineError,
)

__version__ = "0.1.0"

__all__ = [
    "Detection",
    "DetectionEvent",
    "FrameMetadata",
    "ModelMetadata",
    "NodeHeartbeat",
    "NodeRegistration",
    "PerformanceMetrics",
    "SignedDetectionEnvelope",
    "__version__",
    "canonical_event_bytes",
    "KeyMaterialError",
    "encode_public_key",
    "generate_private_key",
    "load_private_key",
    "load_public_key",
    "serialize_private_key",
    "sign_detection_event",
    "verify_detection_envelope",
    "EventSecurityConfigurationError",
    "EventSecurityDecision",
    "EventSecurityReason",
    "EventSecurityRejection",
    "ReplayFreshnessPolicy",
    "ACCEPTED_STATUS",
    "DETECTION_PATH",
    "HEARTBEAT_PATH",
    "EventTransport",
    "HeartbeatError",
    "HeartbeatFactory",
    "SignedWorkerRunner",
    "SignedWorkerTransport",
    "TransportError",
    "WaitFunction",
    "WorkerHeartbeatLifecycle",
    "DetectorBackend",
    "LocalYOLODetector",
    "LocalYoloDetector",
    "ModelFactory",
    "VisionError",
    "VisionResult",
    "YoloDetector",
    "create_yolo_detector",
    "detect_frame",
    "infer_frame",
    "CapturedFrame",
    "CaptureBackend",
    "CaptureFactory",
    "EventSink",
    "FrameDetector",
    "FrameSource",
    "IdentifierFactory",
    "MonotonicClock",
    "OpenCvFrameSource",
    "PrivacyWorkerPipeline",
    "UtcClock",
    "WorkerLifecycle",
    "WorkerPipelineError",
]
