.PHONY: bootstrap keys test lint up down demo attack experiment verify-runs

bootstrap:
	uv sync --dev

keys:
	@echo "Key generation is queued for the Milestone 1 security task; no keys are generated by the foundation."
	@exit 2

test:
	python -m pytest

lint:
	python -m ruff check .
	python -m mypy secureedge apps

up:
	docker compose up --build

down:
	docker compose down

demo:
	@echo "The supervisor demo will be enabled after the privacy-mode vertical slice is integrated."
	@exit 2

attack:
	@echo "Attack adapters are reserved for Milestone 2."
	@exit 2

experiment:
	@echo "Experiment runs are reserved for Milestone 3."
	@exit 2

verify-runs:
	@echo "Run-artifact verification is reserved for Milestone 3."
	@exit 2
